# Meteor.startup ->
#   if Threads.find().count() == 0
#     Threads.insert(threadId: 1, noteId: Notes.findOne( {noteId: 219} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "33rockyknob@gmail.com"} } })._id)
#     Threads.insert(threadId: 2, noteId: Notes.findOne( {noteId: 137} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "64mustang@ameritech.net"} } })._id)
#     Threads.insert(threadId: 3, noteId: Notes.findOne( {noteId: 297} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "AAG@HCI.NET"} } })._id)
#     Threads.insert(threadId: 4, noteId: Notes.findOne( {noteId: 247} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "APatton@eprod.com"} } })._id)
#     Threads.insert(threadId: 5, noteId: Notes.findOne( {noteId: 69} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "apollo18@wedtv.net"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "raymond.garceau@att.net"} } })._id)
#     Threads.insert(threadId: 6, noteId: Notes.findOne( {noteId: 111} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "apollo18@wedtv.net"} } })._id)
#     Threads.insert(threadId: 7, noteId: Notes.findOne( {noteId: 152} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "asku3@verizon.net"} } })._id)
#     Threads.insert(threadId: 8, noteId: Notes.findOne( {noteId: 260} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "Barraccus@aol.com"} } })._id)
#     Threads.insert(threadId: 9, noteId: Notes.findOne( {noteId: 295} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "bevdnewsome@yahoo.com"} } })._id)
#     Threads.insert(threadId: 10, noteId: Notes.findOne( {noteId: 300} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "BOARD617@ATT.NET"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "hartlej5354@gmail.com"} } })._id)
#     Threads.insert(threadId: 11, noteId: Notes.findOne( {noteId: 77} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "Bocoman@aol.com"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "dews327@yahoo.com"} } })._id)
#     Threads.insert(threadId: 12, noteId: Notes.findOne( {noteId: 216} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "Bossadagang2@msn.com"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "ssab44@yahoo.com"} } })._id)
#     Threads.insert(threadId: 13, noteId: Notes.findOne( {noteId: 27} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "Bracymarion@aol.com"} } })._id)
#     Threads.insert(threadId: 14, noteId: Notes.findOne( {noteId: 90} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "Bracymarion@aol.com"} } })._id)
#     Threads.insert(threadId: 15, noteId: Notes.findOne( {noteId: 63} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "BUCROSPAR3@AOL.COM"} } })._id)
#     Threads.insert(threadId: 16, noteId: Notes.findOne( {noteId: 32} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "Cakes1@aol.com"} } })._id)
#     Threads.insert(threadId: 17, noteId: Notes.findOne( {noteId: 195} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "Cakes1@aol.com"} } })._id)
#     Threads.insert(threadId: 18, noteId: Notes.findOne( {noteId: 126} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "carlbgrimmett@comcast.net"} } })._id)
#     Threads.insert(threadId: 19, noteId: Notes.findOne( {noteId: 148} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "chiefsailor@msn.com"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "Mrbeard1@aol.com"} } })._id)
#     Threads.insert(threadId: 20, noteId: Notes.findOne( {noteId: 119} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "clarence@tds.net"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "bjhdd710@cox.net"} } })._id)
#     Threads.insert(threadId: 21, noteId: Notes.findOne( {noteId: 294} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "clarence@tds.net"} } })._id)
#     Threads.insert(threadId: 22, noteId: Notes.findOne( {noteId: 36} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "compasslaka@peoplepc.com"} } })._id)
#     Threads.insert(threadId: 23, noteId: Notes.findOne( {noteId: 143} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "davedavies1961@msn.com"} } })._id)
#     Threads.insert(threadId: 24, noteId: Notes.findOne( {noteId: 196} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "dd710@bellsouth.net"} } })._id)
#     Threads.insert(threadId: 25, noteId: Notes.findOne( {noteId: 153} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "delgearing@wavmax.com"} } })._id)
#     Threads.insert(threadId: 26, noteId: Notes.findOne( {noteId: 177} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "DiLullo@prodigy.net"} } })._id)
#     Threads.insert(threadId: 27, noteId: Notes.findOne( {noteId: 235} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "djar4@hotmail.com"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "DalePotter@ATT.NET"} } })._id)
#     Threads.insert(threadId: 28, noteId: Notes.findOne( {noteId: 136} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "DMVendingRepair@aol.com"} } })._id)
#     Threads.insert(threadId: 29, noteId: Notes.findOne( {noteId: 236} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "donbenchoff@comcast.net"} } })._id)
#     Threads.insert(threadId: 30, noteId: Notes.findOne( {noteId: 112} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "DTPISSOS@AOL.COM"} } })._id)
#     Threads.insert(threadId: 31, noteId: Notes.findOne( {noteId: 213} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "edelrick0@verizon.net"} } })._id)
#     Threads.insert(threadId: 32, noteId: Notes.findOne( {noteId: 45} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "edmccabe@midohio.net"} } })._id)
#     Threads.insert(threadId: 33, noteId: Notes.findOne( {noteId: 49} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "ervingaylard@hotmail.com"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "neilsdeals231@cs.com"} } })._id)
#     Threads.insert(threadId: 34, noteId: Notes.findOne( {noteId: 130} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "ferencsik@msn.com"} } })._id)
#     Threads.insert(threadId: 35, noteId: Notes.findOne( {noteId: 165} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "ferencsik@msn.com"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "sgtdsd@hotmail.com"} } })._id)
#     Threads.insert(threadId: 36, noteId: Notes.findOne( {noteId: 124} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "fladevfund@aol.com"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "dickhanley17@cox.net"} } })._id)
#     Threads.insert(threadId: 37, noteId: Notes.findOne( {noteId: 20} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "franks53@suddenlink.net"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "WAYPER@zoominternet.net"} } })._id)
#     Threads.insert(threadId: 38, noteId: Notes.findOne( {noteId: 144} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "frost103710@msn.com"} } })._id)
#     Threads.insert(threadId: 39, noteId: Notes.findOne( {noteId: 142} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "garyelwood45@hotmail.com"} } })._id)
#     Threads.insert(threadId: 40, noteId: Notes.findOne( {noteId: 285} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "garyelwood45@hotmail.com"} } })._id)
#     Threads.insert(threadId: 41, noteId: Notes.findOne( {noteId: 125} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "goodwr3@pa.net"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "bdmcswain@cox.net"} } })._id)
#     Threads.insert(threadId: 42, noteId: Notes.findOne( {noteId: 200} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "gzarbano@dcwisp.net"} } })._id)
#     Threads.insert(threadId: 43, noteId: Notes.findOne( {noteId: 175} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "hrmasnik@gmail.com"} } })._id)
#     Threads.insert(threadId: 44, noteId: Notes.findOne( {noteId: 253} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "hubbard333@hotmail.com"} } })._id)
#     Threads.insert(threadId: 45, noteId: Notes.findOne( {noteId: 40} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "HWallsJOAN@aol.com"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "richoverton@verizon.net"} } })._id)
#     Threads.insert(threadId: 46, noteId: Notes.findOne( {noteId: 194} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "hyoung10@comcast.net"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "timhwade@knology.net"} } })._id)
#     Threads.insert(threadId: 47, noteId: Notes.findOne( {noteId: 169} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "jameszang555@hotmail.com"} } })._id)
#     Threads.insert(threadId: 48, noteId: Notes.findOne( {noteId: 242} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "janneep@mailstation.com"} } })._id)
#     Threads.insert(threadId: 49, noteId: Notes.findOne( {noteId: 256} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "jc852@aol.com"} } })._id)
#     Threads.insert(threadId: 50, noteId: Notes.findOne( {noteId: 211} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "jdaniel999@aol.com"} } })._id)
#     Threads.insert(threadId: 51, noteId: Notes.findOne( {noteId: 75} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "jdeigan@erols.com"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "RLSSTONE@sbcglobal.net"} } })._id)
#     Threads.insert(threadId: 52, noteId: Notes.findOne( {noteId: 171} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "jdeigan@erols.com"} } })._id)
#     Threads.insert(threadId: 53, noteId: Notes.findOne( {noteId: 48} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "jmwallace54@comcast.net"} } })._id)
#     Threads.insert(threadId: 54, noteId: Notes.findOne( {noteId: 269} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "joycecoy@aol.com"} } })._id)
#     Threads.insert(threadId: 55, noteId: Notes.findOne( {noteId: 42} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "jrk540@q.com"} } })._id)
#     Threads.insert(threadId: 56, noteId: Notes.findOne( {noteId: 102} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "JSHowie@mediaone.net"} } })._id)
#     Threads.insert(threadId: 57, noteId: Notes.findOne( {noteId: 29} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "jthibadeau@gmail.com"} } })._id)
#     Threads.insert(threadId: 58, noteId: Notes.findOne( {noteId: 60} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "jthibadeau@gmail.com"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "jdhoeschen@charter.net"} } })._id)
#     Threads.insert(threadId: 59, noteId: Notes.findOne( {noteId: 57} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "kbaker4640@aol.com"} } })._id)
#     Threads.insert(threadId: 60, noteId: Notes.findOne( {noteId: 91} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "kebrooks@snet.net"} } })._id)
#     Threads.insert(threadId: 61, noteId: Notes.findOne( {noteId: 44} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "kenwarner@worldnet.att.net"} } })._id)
#     Threads.insert(threadId: 62, noteId: Notes.findOne( {noteId: 244} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "kmoh13@msn.com"} } })._id)
#     Threads.insert(threadId: 63, noteId: Notes.findOne( {noteId: 147} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "KRALS2915@sbcglobal.NET"} } })._id)
#     Threads.insert(threadId: 64, noteId: Notes.findOne( {noteId: 289} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "ld.naone@verizon.net"} } })._id)
#     Threads.insert(threadId: 65, noteId: Notes.findOne( {noteId: 270} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "lee73120@aol.com"} } })._id)
#     Threads.insert(threadId: 66, noteId: Notes.findOne( {noteId: 51} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "lennypessin@yahoo.com"} } })._id)
#     Threads.insert(threadId: 67, noteId: Notes.findOne( {noteId: 158} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "Leosroar7@comcast.net"} } })._id)
#     Threads.insert(threadId: 68, noteId: Notes.findOne( {noteId: 193} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "LES710@verizon.net"} } })._id)
#     Threads.insert(threadId: 69, noteId: Notes.findOne( {noteId: 89} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "lowdog@twlakes.net"} } })._id)
#     Threads.insert(threadId: 70, noteId: Notes.findOne( {noteId: 170} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "lowdog@twlakes.net"} } })._id)
#     Threads.insert(threadId: 71, noteId: Notes.findOne( {noteId: 18} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "magokay@hotmail.com"} } })._id)
#     Threads.insert(threadId: 72, noteId: Notes.findOne( {noteId: 134} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "mamkrm@att.net"} } })._id)
#     Threads.insert(threadId: 73, noteId: Notes.findOne( {noteId: 231} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "mamkrm@att.net"} } })._id)
#     Threads.insert(threadId: 74, noteId: Notes.findOne( {noteId: 209} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "mattingly4447@windstream.net"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "Edward.Kubisek@HP.com"} } })._id)
#     Threads.insert(threadId: 75, noteId: Notes.findOne( {noteId: 255} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "maxwell62@verizon.net"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "margieericksen@gmail.com"} } })._id)
#     Threads.insert(threadId: 76, noteId: Notes.findOne( {noteId: 50} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "MceVoy-M@subway.com"} } })._id)
#     Threads.insert(threadId: 77, noteId: Notes.findOne( {noteId: 227} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "MceVoy-M@subway.com"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "mazzeoo@sbcglobal.net"} } })._id)
#     Threads.insert(threadId: 78, noteId: Notes.findOne( {noteId: 192} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "mdcjeep@aol.com"} } })._id)
#     Threads.insert(threadId: 79, noteId: Notes.findOne( {noteId: 286} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "mikemccaffree@gmail.com"} } })._id)
#     Threads.insert(threadId: 80, noteId: Notes.findOne( {noteId: 65} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "morganjnc@seii.net"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "lindacrossfield1@gmail.com"} } })._id)
#     Threads.insert(threadId: 81, noteId: Notes.findOne( {noteId: 39} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "MPaup@prodigy.net"} } })._id)
#     Threads.insert(threadId: 82, noteId: Notes.findOne( {noteId: 56} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "mprocelli@msn.com"} } })._id)
#     Threads.insert(threadId: 83, noteId: Notes.findOne( {noteId: 80} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "MSMEISLIN@ADELPHIA.NET"} } })._id)
#     Threads.insert(threadId: 84, noteId: Notes.findOne( {noteId: 66} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "mv1313@yahoo.com"} } })._id)
#     Threads.insert(threadId: 85, noteId: Notes.findOne( {noteId: 16} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "nancymc51@aol.com"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "svferguson@optonline.net"} } })._id)
#     Threads.insert(threadId: 86, noteId: Notes.findOne( {noteId: 41} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "nancymc51@aol.com"} } })._id)
#     Threads.insert(threadId: 87, noteId: Notes.findOne( {noteId: 72} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "neat@ameritech.net"} } })._id)
#     Threads.insert(threadId: 88, noteId: Notes.findOne( {noteId: 290} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "need4speed60@earthlink.net"} } })._id)
#     Threads.insert(threadId: 89, noteId: Notes.findOne( {noteId: 81} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "nynex01@verizon.net"} } })._id)
#     Threads.insert(threadId: 90, noteId: Notes.findOne( {noteId: 173} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "nynex01@verizon.net"} } })._id)
#     Threads.insert(threadId: 91, noteId: Notes.findOne( {noteId: 221} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "oharabs@gmail.com"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "debrickkinder@aol.com"} } })._id)
#     Threads.insert(threadId: 92, noteId: Notes.findOne( {noteId: 133} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "paulshep@ev1.net"} } })._id)
#     Threads.insert(threadId: 93, noteId: Notes.findOne( {noteId: 94} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "pitts@tampabay.rr.com"} } })._id)
#     Threads.insert(threadId: 94, noteId: Notes.findOne( {noteId: 207} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "pitts@tampabay.rr.com"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "wsmcfadden@comcast.net"} } })._id)
#     Threads.insert(threadId: 95, noteId: Notes.findOne( {noteId: 9} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "PWDEAL@earthlink.NET"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "HMHAVERS@CS.COM"} } })._id)
#     Threads.insert(threadId: 96, noteId: Notes.findOne( {noteId: 201} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "PWDEAL@earthlink.NET"} } })._id)
#     Threads.insert(threadId: 97, noteId: Notes.findOne( {noteId: 122} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "R_SHILLINGTON@YAHOO.COM"} } })._id)
#     Threads.insert(threadId: 98, noteId: Notes.findOne( {noteId: 178} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "R_SHILLINGTON@YAHOO.COM"} } })._id)
#     Threads.insert(threadId: 99, noteId: Notes.findOne( {noteId: 230} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "rflynn-cv9@juno.com"} } })._id)
#     Threads.insert(threadId: 100, noteId: Notes.findOne( {noteId: 4} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "rhendricks21@comcast.net"} } })._id)
#     Threads.insert(threadId: 101, noteId: Notes.findOne( {noteId: 166} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "rhendricks21@comcast.net"} } })._id)
#     Threads.insert(threadId: 102, noteId: Notes.findOne( {noteId: 1} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "ricster@fast.net"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "frconsidine@gmail.com"} } })._id)
#     Threads.insert(threadId: 103, noteId: Notes.findOne( {noteId: 160} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "rlalphonse@sault.com"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "james9398@verizon.net"} } })._id)
#     Threads.insert(threadId: 104, noteId: Notes.findOne( {noteId: 214} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "rlirei@peoplepc.com"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "RES330@aol.com"} } })._id)
#     Threads.insert(threadId: 105, noteId: Notes.findOne( {noteId: 258} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "rlstoecker@earthlink.net"} } })._id)
#     Threads.insert(threadId: 106, noteId: Notes.findOne( {noteId: 146} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "rondo@adelphia.net"} } })._id)
#     Threads.insert(threadId: 107, noteId: Notes.findOne( {noteId: 296} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "RPSmith116@aol.com"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "SPATSESQ@aol.com"} } })._id)
#     Threads.insert(threadId: 108, noteId: Notes.findOne( {noteId: 121} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "rvose@netway.com"} } })._id)
#     Threads.insert(threadId: 109, noteId: Notes.findOne( {noteId: 222} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "rvose@netway.com"} } })._id)
#     Threads.insert(threadId: 110, noteId: Notes.findOne( {noteId: 240} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "rvose@netway.com"} } })._id)
#     Threads.insert(threadId: 111, noteId: Notes.findOne( {noteId: 183} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "sjohns55@tampabay.rr.com"} } })._id)
#     Threads.insert(threadId: 112, noteId: Notes.findOne( {noteId: 225} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "SJSYLVESTER1@adelphia.net"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "johnjumper@msn.com"} } })._id)
#     Threads.insert(threadId: 113, noteId: Notes.findOne( {noteId: 159} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "sklors@hotmail.com"} } })._id)
#     Threads.insert(threadId: 114, noteId: Notes.findOne( {noteId: 114} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "srburr@comcast.net"} } })._id)
#     Threads.insert(threadId: 115, noteId: Notes.findOne( {noteId: 267} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "steven.p.rice@worldnet.att.net"} } })._id)
#     Threads.insert(threadId: 116, noteId: Notes.findOne( {noteId: 26} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "stevep@psu.edu"} } })._id)
#     Threads.insert(threadId: 117, noteId: Notes.findOne( {noteId: 243} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "tgrip1@sisna.com"} } })._id)
#     Threads.insert(threadId: 118, noteId: Notes.findOne( {noteId: 179} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "TKMartin@Unforgettable.com"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "GFFAY13@GMAIL.COM"} } })._id)
#     Threads.insert(threadId: 119, noteId: Notes.findOne( {noteId: 220} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "tmanos@concursive.com"} } })._id)
#     Threads.insert(threadId: 120, noteId: Notes.findOne( {noteId: 257} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "Trailblazer710@aol.com"} } })._id)
#     Threads.insert(threadId: 121, noteId: Notes.findOne( {noteId: 19} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "TRHemail@aol.com"} } })._id)
#     Threads.insert(threadId: 122, noteId: Notes.findOne( {noteId: 25} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "TRHemail@aol.com"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "jcp@mountainmax.net"} } })._id)
#     Threads.insert(threadId: 123, noteId: Notes.findOne( {noteId: 223} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "TRHemail@aol.com"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "Rjksteele@aol.com"} } })._id)
#     Threads.insert(threadId: 124, noteId: Notes.findOne( {noteId: 150} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "volzins@mchsi.com"} } })._id, responderId: Meteor.users.findOne({emails: {$elemMatch: {address: "jimbob815@juno.com"} } })._id)
#     Threads.insert(threadId: 125, noteId: Notes.findOne( {noteId: 210} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "vthrall@frontiernet.net"} } })._id)
#     Threads.insert(threadId: 126, noteId: Notes.findOne( {noteId: 55} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "washburn.arthur3@gmail.com"} } })._id)
#     Threads.insert(threadId: 127, noteId: Notes.findOne( {noteId: 83} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "wb0ytj@juno.com"} } })._id)
#     Threads.insert(threadId: 128, noteId: Notes.findOne( {noteId: 168} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "wb0ytj@juno.com"} } })._id)
#     Threads.insert(threadId: 129, noteId: Notes.findOne( {noteId: 120} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "WBRUCEEVANS@BELLSOUTH.NET"} } })._id)
#     Threads.insert(threadId: 130, noteId: Notes.findOne( {noteId: 7} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "wchandler098@comcast.net"} } })._id)
#     Threads.insert(threadId: 131, noteId: Notes.findOne( {noteId: 31} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "WPRINCE1@AOL.COM"} } })._id)
#     Threads.insert(threadId: 132, noteId: Notes.findOne( {noteId: 291} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "wrmrgr2@sbcglobal.net"} } })._id)
#     Threads.insert(threadId: 133, noteId: Notes.findOne( {noteId: 264} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "WWWJAW@aol.com"} } })._id)
#     Threads.insert(threadId: 134, noteId: Notes.findOne( {noteId: 2} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "lmpcnp@comcast.net"} } })._id)
#     Threads.insert(threadId: 135, noteId: Notes.findOne( {noteId: 3} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "Jerrygutschow1@gmail.com"} } })._id)
#     Threads.insert(threadId: 136, noteId: Notes.findOne( {noteId: 5} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "Prosale@aol.com"} } })._id)
#     Threads.insert(threadId: 137, noteId: Notes.findOne( {noteId: 6} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "johnjumper@msn.com"} } })._id)
#     Threads.insert(threadId: 138, noteId: Notes.findOne( {noteId: 8} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "rhendricks21@comcast.net"} } })._id)
#     Threads.insert(threadId: 139, noteId: Notes.findOne( {noteId: 10} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "clintchc@aol.com"} } })._id)
#     Threads.insert(threadId: 140, noteId: Notes.findOne( {noteId: 11} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "RKirsch9649@hotmail.com"} } })._id)
#     Threads.insert(threadId: 141, noteId: Notes.findOne( {noteId: 12} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "vthrall@frontiernet.net"} } })._id)
#     Threads.insert(threadId: 142, noteId: Notes.findOne( {noteId: 13} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "DennFrdd@AOL.COM"} } })._id)
#     Threads.insert(threadId: 143, noteId: Notes.findOne( {noteId: 14} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "hjimwilson@aol.com"} } })._id)
#     Threads.insert(threadId: 144, noteId: Notes.findOne( {noteId: 15} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "JOEMREILLY@YAHOO.COM"} } })._id)
#     Threads.insert(threadId: 145, noteId: Notes.findOne( {noteId: 17} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "ssab44@yahoo.com"} } })._id)
#     Threads.insert(threadId: 146, noteId: Notes.findOne( {noteId: 21} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "rvose@netway.com"} } })._id)
#     Threads.insert(threadId: 147, noteId: Notes.findOne( {noteId: 22} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "hhumphre@dreamscape.com"} } })._id)
#     Threads.insert(threadId: 148, noteId: Notes.findOne( {noteId: 23} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "Golfer735@aol.com"} } })._id)
#     Threads.insert(threadId: 149, noteId: Notes.findOne( {noteId: 24} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "RAYMART1@OPTONLINE.NET"} } })._id)
#     Threads.insert(threadId: 150, noteId: Notes.findOne( {noteId: 28} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "marilyn-lockwood@sbcglobal.net"} } })._id)
#     Threads.insert(threadId: 151, noteId: Notes.findOne( {noteId: 30} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "mdcjeep@aol.com"} } })._id)
#     Threads.insert(threadId: 152, noteId: Notes.findOne( {noteId: 33} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "djc47@sbcglobal.net"} } })._id)
#     Threads.insert(threadId: 153, noteId: Notes.findOne( {noteId: 34} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "melvinst6@gmail.com"} } })._id)
#     Threads.insert(threadId: 154, noteId: Notes.findOne( {noteId: 35} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "maxwell62@verizon.net"} } })._id)
#     Threads.insert(threadId: 155, noteId: Notes.findOne( {noteId: 37} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "bbullens@charter.net"} } })._id)
#     Threads.insert(threadId: 156, noteId: Notes.findOne( {noteId: 38} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "rhendricks21@comcast.net"} } })._id)
#     Threads.insert(threadId: 157, noteId: Notes.findOne( {noteId: 43} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "WPRINCE1@AOL.COM"} } })._id)
#     Threads.insert(threadId: 158, noteId: Notes.findOne( {noteId: 46} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "larryandkip@echoes.net"} } })._id)
#     Threads.insert(threadId: 159, noteId: Notes.findOne( {noteId: 47} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "cathrinebs@sbcglobal.net"} } })._id)
#     Threads.insert(threadId: 160, noteId: Notes.findOne( {noteId: 52} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "HAL@ARM-TEK.COM"} } })._id)
#     Threads.insert(threadId: 161, noteId: Notes.findOne( {noteId: 53} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "wwwduceadd@aol.com"} } })._id)
#     Threads.insert(threadId: 162, noteId: Notes.findOne( {noteId: 54} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "orrjf@wowway.com"} } })._id)
#     Threads.insert(threadId: 163, noteId: Notes.findOne( {noteId: 58} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "kmoh13@msn.com"} } })._id)
#     Threads.insert(threadId: 164, noteId: Notes.findOne( {noteId: 59} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "donprov@optonline.net"} } })._id)
#     Threads.insert(threadId: 165, noteId: Notes.findOne( {noteId: 61} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "Trailblazer710@aol.com"} } })._id)
#     Threads.insert(threadId: 166, noteId: Notes.findOne( {noteId: 62} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "Mrbeard1@aol.com"} } })._id)
#     Threads.insert(threadId: 167, noteId: Notes.findOne( {noteId: 64} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "RKARCHER@MSN.COM"} } })._id)
#     Threads.insert(threadId: 168, noteId: Notes.findOne( {noteId: 67} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "gzarbano@dcwisp.net"} } })._id)
#     Threads.insert(threadId: 169, noteId: Notes.findOne( {noteId: 68} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "alicearnie@aol.com"} } })._id)
#     Threads.insert(threadId: 170, noteId: Notes.findOne( {noteId: 70} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "jadeyounglee@yahoo.com"} } })._id)
#     Threads.insert(threadId: 171, noteId: Notes.findOne( {noteId: 71} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "raymond.garceau@att.net"} } })._id)
#     Threads.insert(threadId: 172, noteId: Notes.findOne( {noteId: 73} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "mdcjeep@aol.com"} } })._id)
#     Threads.insert(threadId: 173, noteId: Notes.findOne( {noteId: 74} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "SJSYLVESTER1@adelphia.net"} } })._id)
#     Threads.insert(threadId: 174, noteId: Notes.findOne( {noteId: 76} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "bjhdd710@cox.net"} } })._id)
#     Threads.insert(threadId: 175, noteId: Notes.findOne( {noteId: 78} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "vkraft15@comcast.net"} } })._id)
#     Threads.insert(threadId: 176, noteId: Notes.findOne( {noteId: 79} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "lsvidoli@verizon.net"} } })._id)
#     Threads.insert(threadId: 177, noteId: Notes.findOne( {noteId: 82} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "ostermeyer@verizon.net"} } })._id)
#     Threads.insert(threadId: 178, noteId: Notes.findOne( {noteId: 84} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "clintchc@aol.com"} } })._id)
#     Threads.insert(threadId: 179, noteId: Notes.findOne( {noteId: 85} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "burton530@verizon.net"} } })._id)
#     Threads.insert(threadId: 180, noteId: Notes.findOne( {noteId: 86} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "simpsonjoe@comcast.net"} } })._id)
#     Threads.insert(threadId: 181, noteId: Notes.findOne( {noteId: 87} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "shodig@dmv.com"} } })._id)
#     Threads.insert(threadId: 182, noteId: Notes.findOne( {noteId: 88} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "o551@yahoo.com"} } })._id)
#     Threads.insert(threadId: 183, noteId: Notes.findOne( {noteId: 92} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "vthrall@frontiernet.net"} } })._id)
#     Threads.insert(threadId: 184, noteId: Notes.findOne( {noteId: 93} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "dalenjude@gmail.com"} } })._id)
#     Threads.insert(threadId: 185, noteId: Notes.findOne( {noteId: 95} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "TRHemail@aol.com"} } })._id)
#     Threads.insert(threadId: 186, noteId: Notes.findOne( {noteId: 96} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "DADaurelio@neo.rr.com"} } })._id)
#     Threads.insert(threadId: 187, noteId: Notes.findOne( {noteId: 97} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "donbell1934@verizon.net"} } })._id)
#     Threads.insert(threadId: 188, noteId: Notes.findOne( {noteId: 98} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "thomiv@iowatelecom.net"} } })._id)
#     Threads.insert(threadId: 189, noteId: Notes.findOne( {noteId: 99} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "mikemccaffree@gmail.com"} } })._id)
#     Threads.insert(threadId: 190, noteId: Notes.findOne( {noteId: 100} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "budlin@ellijay.com"} } })._id)
#     Threads.insert(threadId: 191, noteId: Notes.findOne( {noteId: 101} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "pamela.putinas@att.net"} } })._id)
#     Threads.insert(threadId: 192, noteId: Notes.findOne( {noteId: 103} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "lg@shapirosher.com"} } })._id)
#     Threads.insert(threadId: 193, noteId: Notes.findOne( {noteId: 104} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "arlie@mywesleycommons.org"} } })._id)
#     Threads.insert(threadId: 194, noteId: Notes.findOne( {noteId: 105} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "csmikm@gmail.com"} } })._id)
#     Threads.insert(threadId: 195, noteId: Notes.findOne( {noteId: 106} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "moosefan35@yahoo.com"} } })._id)
#     Threads.insert(threadId: 196, noteId: Notes.findOne( {noteId: 107} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "paulct1951@earthlink.net"} } })._id)
#     Threads.insert(threadId: 197, noteId: Notes.findOne( {noteId: 108} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "cecil@cecilgunter.com"} } })._id)
#     Threads.insert(threadId: 198, noteId: Notes.findOne( {noteId: 109} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "Peter@sbcglobal.net"} } })._id)
#     Threads.insert(threadId: 199, noteId: Notes.findOne( {noteId: 110} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "dgenier@insightbb.com"} } })._id)
#     Threads.insert(threadId: 200, noteId: Notes.findOne( {noteId: 113} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "THKK@aol.com"} } })._id)
#     Threads.insert(threadId: 201, noteId: Notes.findOne( {noteId: 115} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "patandcarl9@comcast.net"} } })._id)
#     Threads.insert(threadId: 202, noteId: Notes.findOne( {noteId: 116} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "lenholmberg@msn.com"} } })._id)
#     Threads.insert(threadId: 203, noteId: Notes.findOne( {noteId: 117} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "oakessteve@hotmail.com"} } })._id)
#     Threads.insert(threadId: 204, noteId: Notes.findOne( {noteId: 118} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "bill.pillow@yahoo.com"} } })._id)
#     Threads.insert(threadId: 205, noteId: Notes.findOne( {noteId: 123} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "chief12046@yahoo.com"} } })._id)
#     Threads.insert(threadId: 206, noteId: Notes.findOne( {noteId: 127} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "madrad13@verizon.net"} } })._id)
#     Threads.insert(threadId: 207, noteId: Notes.findOne( {noteId: 128} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "joycecoy@aol.com"} } })._id)
#     Threads.insert(threadId: 208, noteId: Notes.findOne( {noteId: 129} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "MceVoy-M@subway.com"} } })._id)
#     Threads.insert(threadId: 209, noteId: Notes.findOne( {noteId: 131} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "WPRINCE1@AOL.COM"} } })._id)
#     Threads.insert(threadId: 210, noteId: Notes.findOne( {noteId: 132} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "washburn.arthur3@gmail.com"} } })._id)
#     Threads.insert(threadId: 211, noteId: Notes.findOne( {noteId: 135} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "ronwaxon@msn.com"} } })._id)
#     Threads.insert(threadId: 212, noteId: Notes.findOne( {noteId: 138} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "NUCLEARBT@AOL.COM"} } })._id)
#     Threads.insert(threadId: 213, noteId: Notes.findOne( {noteId: 139} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "kenwarner@worldnet.att.net"} } })._id)
#     Threads.insert(threadId: 214, noteId: Notes.findOne( {noteId: 140} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "smithp-b@cox.net"} } })._id)
#     Threads.insert(threadId: 215, noteId: Notes.findOne( {noteId: 141} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "Peter@sbcglobal.net"} } })._id)
#     Threads.insert(threadId: 216, noteId: Notes.findOne( {noteId: 145} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "albs56@aol.com"} } })._id)
#     Threads.insert(threadId: 217, noteId: Notes.findOne( {noteId: 149} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "DalePotter@ATT.NET"} } })._id)
#     Threads.insert(threadId: 218, noteId: Notes.findOne( {noteId: 151} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "james9398@verizon.net"} } })._id)
#     Threads.insert(threadId: 219, noteId: Notes.findOne( {noteId: 154} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "cardinal1771@comcast.net"} } })._id)
#     Threads.insert(threadId: 220, noteId: Notes.findOne( {noteId: 155} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "donbarnes@aol.com"} } })._id)
#     Threads.insert(threadId: 221, noteId: Notes.findOne( {noteId: 156} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "lsvidoli@verizon.net"} } })._id)
#     Threads.insert(threadId: 222, noteId: Notes.findOne( {noteId: 157} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "bill.heine@snet.net"} } })._id)
#     Threads.insert(threadId: 223, noteId: Notes.findOne( {noteId: 161} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "PWDEAL@earthlink.NET"} } })._id)
#     Threads.insert(threadId: 224, noteId: Notes.findOne( {noteId: 162} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "washburn.arthur3@gmail.com"} } })._id)
#     Threads.insert(threadId: 225, noteId: Notes.findOne( {noteId: 163} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "TRHemail@aol.com"} } })._id)
#     Threads.insert(threadId: 226, noteId: Notes.findOne( {noteId: 164} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "cowman9898@aol.com"} } })._id)
#     Threads.insert(threadId: 227, noteId: Notes.findOne( {noteId: 167} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "shipwreckkelly@gmail.com"} } })._id)
#     Threads.insert(threadId: 228, noteId: Notes.findOne( {noteId: 172} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "ricster@fast.net"} } })._id)
#     Threads.insert(threadId: 229, noteId: Notes.findOne( {noteId: 174} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "vdyne@att.net"} } })._id)
#     Threads.insert(threadId: 230, noteId: Notes.findOne( {noteId: 176} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "BerLinermutti@comcast.net"} } })._id)
#     Threads.insert(threadId: 231, noteId: Notes.findOne( {noteId: 180} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "donbarnes@aol.com"} } })._id)
#     Threads.insert(threadId: 232, noteId: Notes.findOne( {noteId: 181} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "joelbcovington@gmail.com"} } })._id)
#     Threads.insert(threadId: 233, noteId: Notes.findOne( {noteId: 182} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "halhollingsworth@aol.com"} } })._id)
#     Threads.insert(threadId: 234, noteId: Notes.findOne( {noteId: 184} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "budlin@ellijay.com"} } })._id)
#     Threads.insert(threadId: 235, noteId: Notes.findOne( {noteId: 185} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "lmpcnp@comcast.net"} } })._id)
#     Threads.insert(threadId: 236, noteId: Notes.findOne( {noteId: 186} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "raymond.garceau@att.net"} } })._id)
#     Threads.insert(threadId: 237, noteId: Notes.findOne( {noteId: 187} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "raymond.garceau@att.net"} } })._id)
#     Threads.insert(threadId: 238, noteId: Notes.findOne( {noteId: 188} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "mattingly4447@windstream.net"} } })._id)
#     Threads.insert(threadId: 239, noteId: Notes.findOne( {noteId: 189} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "gramanina@aol.com"} } })._id)
#     Threads.insert(threadId: 240, noteId: Notes.findOne( {noteId: 190} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "dramaqueenmom118@aol.com"} } })._id)
#     Threads.insert(threadId: 241, noteId: Notes.findOne( {noteId: 191} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "nicholaswa@prodigy.net"} } })._id)
#     Threads.insert(threadId: 242, noteId: Notes.findOne( {noteId: 197} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "DiLullo@prodigy.net"} } })._id)
#     Threads.insert(threadId: 243, noteId: Notes.findOne( {noteId: 198} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "richoverton@verizon.net"} } })._id)
#     Threads.insert(threadId: 244, noteId: Notes.findOne( {noteId: 199} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "rbish7@aol.com"} } })._id)
#     Threads.insert(threadId: 245, noteId: Notes.findOne( {noteId: 202} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "nancymc51@aol.com"} } })._id)
#     Threads.insert(threadId: 246, noteId: Notes.findOne( {noteId: 203} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "Golfer735@aol.com"} } })._id)
#     Threads.insert(threadId: 247, noteId: Notes.findOne( {noteId: 204} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "RodnThomps@aol.com"} } })._id)
#     Threads.insert(threadId: 248, noteId: Notes.findOne( {noteId: 205} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "darrell.kuhlmann@yahoo.com"} } })._id)
#     Threads.insert(threadId: 249, noteId: Notes.findOne( {noteId: 206} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "SQAWBETTY@AOL.COM"} } })._id)
#     Threads.insert(threadId: 250, noteId: Notes.findOne( {noteId: 208} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "Leosroar7@comcast.net"} } })._id)
#     Threads.insert(threadId: 251, noteId: Notes.findOne( {noteId: 212} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "alfranbensam@charter.net"} } })._id)
#     Threads.insert(threadId: 252, noteId: Notes.findOne( {noteId: 215} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "svferguson@optonline.net"} } })._id)
#     Threads.insert(threadId: 253, noteId: Notes.findOne( {noteId: 217} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "jimpeiffersr@gmail.com"} } })._id)
#     Threads.insert(threadId: 254, noteId: Notes.findOne( {noteId: 218} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "doppenheim@mtginc.com"} } })._id)
#     Threads.insert(threadId: 255, noteId: Notes.findOne( {noteId: 224} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "rbinhood0063@aol.com"} } })._id)
#     Threads.insert(threadId: 256, noteId: Notes.findOne( {noteId: 226} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "raebrevol@yahoo.com"} } })._id)
#     Threads.insert(threadId: 257, noteId: Notes.findOne( {noteId: 228} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "ronwaxon@msn.com"} } })._id)
#     Threads.insert(threadId: 258, noteId: Notes.findOne( {noteId: 229} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "raymond.garceau@att.net"} } })._id)
#     Threads.insert(threadId: 259, noteId: Notes.findOne( {noteId: 232} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "hartlej5354@gmail.com"} } })._id)
#     Threads.insert(threadId: 260, noteId: Notes.findOne( {noteId: 233} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "pamela.putinas@att.net"} } })._id)
#     Threads.insert(threadId: 261, noteId: Notes.findOne( {noteId: 234} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "ldrake002@cinci.rr.com"} } })._id)
#     Threads.insert(threadId: 262, noteId: Notes.findOne( {noteId: 237} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "dolores.emmons@yahoo.com"} } })._id)
#     Threads.insert(threadId: 263, noteId: Notes.findOne( {noteId: 238} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "tsnyder@mindspring.com"} } })._id)
#     Threads.insert(threadId: 264, noteId: Notes.findOne( {noteId: 239} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "PCUNY@zoominternet.net"} } })._id)
#     Threads.insert(threadId: 265, noteId: Notes.findOne( {noteId: 241} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "doppenheim@mtginc.com"} } })._id)
#     Threads.insert(threadId: 266, noteId: Notes.findOne( {noteId: 245} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "lenholmberg@msn.com"} } })._id)
#     Threads.insert(threadId: 267, noteId: Notes.findOne( {noteId: 246} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "DennFrdd@AOL.COM"} } })._id)
#     Threads.insert(threadId: 268, noteId: Notes.findOne( {noteId: 248} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "trmhogan@comcast.net"} } })._id)
#     Threads.insert(threadId: 269, noteId: Notes.findOne( {noteId: 249} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "gramanina@aol.com"} } })._id)
#     Threads.insert(threadId: 270, noteId: Notes.findOne( {noteId: 250} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "djar4@hotmail.com"} } })._id)
#     Threads.insert(threadId: 271, noteId: Notes.findOne( {noteId: 251} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "cadam21@yahoo.com"} } })._id)
#     Threads.insert(threadId: 272, noteId: Notes.findOne( {noteId: 252} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "JAKE7079@hotmail.com"} } })._id)
#     Threads.insert(threadId: 273, noteId: Notes.findOne( {noteId: 254} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "dalenjude@gmail.com"} } })._id)
#     Threads.insert(threadId: 274, noteId: Notes.findOne( {noteId: 259} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "bill@keithtv.com"} } })._id)
#     Threads.insert(threadId: 275, noteId: Notes.findOne( {noteId: 261} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "raebrevol@yahoo.com"} } })._id)
#     Threads.insert(threadId: 276, noteId: Notes.findOne( {noteId: 262} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "lcook55@internet49.com"} } })._id)
#     Threads.insert(threadId: 277, noteId: Notes.findOne( {noteId: 263} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "karenmount@yahoo.com"} } })._id)
#     Threads.insert(threadId: 278, noteId: Notes.findOne( {noteId: 265} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "pdgoebel@fairpoint.net"} } })._id)
#     Threads.insert(threadId: 279, noteId: Notes.findOne( {noteId: 266} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "mapmeilak@charter.net"} } })._id)
#     Threads.insert(threadId: 280, noteId: Notes.findOne( {noteId: 268} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "pamela.putinas@att.net"} } })._id)
#     Threads.insert(threadId: 281, noteId: Notes.findOne( {noteId: 271} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "steven.p.rice@worldnet.att.net"} } })._id)
#     Threads.insert(threadId: 282, noteId: Notes.findOne( {noteId: 272} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "sonya18795@aol.com"} } })._id)
#     Threads.insert(threadId: 283, noteId: Notes.findOne( {noteId: 273} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "mapmeilak@charter.net"} } })._id)
#     Threads.insert(threadId: 284, noteId: Notes.findOne( {noteId: 274} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "kwebster003@tampabay.rr.com"} } })._id)
#     Threads.insert(threadId: 285, noteId: Notes.findOne( {noteId: 275} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "arlie@mywesleycommons.org"} } })._id)
#     Threads.insert(threadId: 286, noteId: Notes.findOne( {noteId: 276} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "mustang714@peoplepc.com"} } })._id)
#     Threads.insert(threadId: 287, noteId: Notes.findOne( {noteId: 277} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "DMGFLG@AOL.COM"} } })._id)
#     Threads.insert(threadId: 288, noteId: Notes.findOne( {noteId: 278} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "Rbattiat@comcast.net"} } })._id)
#     Threads.insert(threadId: 289, noteId: Notes.findOne( {noteId: 279} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "mertcwilson@yahoo.com"} } })._id)
#     Threads.insert(threadId: 290, noteId: Notes.findOne( {noteId: 280} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "jimL4j@yahoo.com"} } })._id)
#     Threads.insert(threadId: 291, noteId: Notes.findOne( {noteId: 281} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "rlirei@peoplepc.com"} } })._id)
#     Threads.insert(threadId: 292, noteId: Notes.findOne( {noteId: 282} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "GBitsoli@cox.net"} } })._id)
#     Threads.insert(threadId: 293, noteId: Notes.findOne( {noteId: 283} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "apollo18@wedtv.net"} } })._id)
#     Threads.insert(threadId: 294, noteId: Notes.findOne( {noteId: 284} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "georgecope@hotmail.com"} } })._id)
#     Threads.insert(threadId: 295, noteId: Notes.findOne( {noteId: 287} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "smith4486@sbcglobal.net"} } })._id)
#     Threads.insert(threadId: 296, noteId: Notes.findOne( {noteId: 288} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "donbenchoff@comcast.net"} } })._id)
#     Threads.insert(threadId: 297, noteId: Notes.findOne( {noteId: 292} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "chuckmaddock@msn.com"} } })._id)
#     Threads.insert(threadId: 298, noteId: Notes.findOne( {noteId: 293} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "jmwallace54@comcast.net"} } })._id)
#     Threads.insert(threadId: 299, noteId: Notes.findOne( {noteId: 298} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "lg@shapirosher.com"} } })._id)
#     Threads.insert(threadId: 300, noteId: Notes.findOne( {noteId: 299} )._id, creatorId: Meteor.users.findOne({emails: {$elemMatch: {address: "DennFrdd@AOL.COM"} } })._id)

